### ISSUE TITLE
INFO:root:No services found on Tobii Glasses 3

### ISSUE THREAD

**Issue by josyulavt** [tobiipro/g3pylib#94]
Hi I'm trying to record the gaze stream and the basic scene stream using python API with the examples file "streamgazerts.py" when I run this file I get the  

```

Traceback (most recent call last):
  File "/home/j/Projects/SeaJay/g3pylib/examples/streamgazertsp.py", line 63, in <module>
    main()
  File "/home/j/Projects/SeaJay/g3pylib/examples/streamgazertsp.py", line 58, in main
    asyncio.run(stream_rtsp())
  File "/home/j/miniconda3/envs/tobii/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/j/miniconda3/envs/tobii/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/j/Projects/SeaJay/g3pylib/examples/streamgazertsp.py", line 14, in stream_rtsp
    async with connect_to_glasses.with_hostname(
  File "/home/j/miniconda3/envs/tobii/lib/python3.10/site-packages/g3pylib/__init__.py", line 315, in __aenter__
    return await self
  File "/home/j/miniconda3/envs/tobii/lib/python3.10/site-packages/g3pylib/__init__.py", line 303, in __await_impl__
    ws_url, rtsp_url, http_url = await self.url_generator
  File "/home/j/miniconda3/envs/tobii/lib/python3.10/site-packages/g3pylib/__init__.py", line 242, in _urls_from_hostname
    service = await G3ServiceDiscovery.request_service(hostname)
  File "/home/j/miniconda3/envs/tobii/lib/python3.10/site-packages/g3pylib/zeroconf.py", line 281, in request_service
    await service.request(async_zeroconf.zeroconf, timeout)
  File "/home/j/miniconda3/envs/tobii/lib/python3.10/site-packages/g3pylib/zeroconf.py", line 147, in request
    raise ServiceNotFoundError
g3pylib.zeroconf.ServiceNotFoundError
```

I was trying to debug this and I tried running the "zeroconfdiscovery.py" which gives the output

```
INFO:root:Listening for glasses3
INFO:root:No services found
INFO:root:Stop listening
```

I'm getting the IMU messages on the "rudimentarystreams.py" 
```

INFO:root:Receiving IMU stream
INFO:root:Received 300 IMU messages
INFO:root:IMU message snapshot: [2.62897626, {'accelerometer': [0.9798405745477999, -1.5756789772131612, -9.707476233997195], 'gyroscope': [-1.8168891299999999, -0.26680614466753827, 5.973127647501231]}]
```

Please help. thank you.

**Comment by mmanzardo99** [comment]
I had the same issue. I tried to open the stream RTSP with VLC and it works. Does someone know which could be the problem?

**Comment by fahadkhan-roboticist** [comment]
Same issue, if anyone could resolve please post
